--  Body file for function ponger
--  Generated by TASTE (kazoo/templates/skeletons/ada-body/function.tmplt)
--  You can edit this file, it will not be overwritten
--
--  !! IMPORTANT                                                        !!
--  !! When you modify your design (interface view), you must update    !!
--  !! the procedures corresponding to the provided interfaces in this  !!
--  !! file. The up-to-date signatures can be found in the .ads file.   !!

with Interfaces; use Interfaces;
package body Ponger is

   procedure Ping (param : in out asn1SccMyinteger) is
         aux : asn1SccMyinteger := 0;
      begin
         aux := param + 2;
         Pong(aux);
      end Ping;

   begin
      null;

end Ponger;

