/* Body file for function ponger
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "ponger.h"
#include <rtems.h>
#include <spw.h>

#define DATA_SIZE 8192U

asn1SccMySeq new_data;

void ponger_startup(void)
{
}

void ponger_PI_ping(const asn1SccMySeq *IN_PI_1)
{
  // Dummy data processing for test purpose
  new_data.test_id = IN_PI_1->test_id + 5;
  new_data.test_destination_id = IN_PI_1->test_destination_id + 5;

  for(uint32_t i = 0; i < DATA_SIZE; i++){
    if(IN_PI_1->test_data.arr[i] == 0xDE){
      new_data.test_data.arr[i] = 0x13;
    }
  }

  ponger_RI_pong(&new_data);
}

