/* Body file for function linux
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "linux.h"
#include <stdio.h>

typedef enum {
    Initial,
    Uart3Test1Sent,
    Uart3Response1Received,
    Uart3Test2Sent,
    Uart3Response2Received,
    Uart1Test1Sent,
    Uart1Response1Received,
    Uart1Test2Sent,
    Uart1Response2Received,
} TestState;

static asn1SccMyInteger test_param = 0;
static TestState test_state = Initial;

void linux_startup(void)
{
}

void linux_PI_response_1
      (const asn1SccMyInteger *IN_param)

{
    if(test_state == Uart1Test1Sent) {
        test_param = *IN_param;
        printf("Got response from UART1: %lu\n", *IN_param);
        test_state = Uart1Response1Received;
    }
    else if(test_state == Uart1Test2Sent) {
        test_param = *IN_param;
        printf("Got response from UART1: %lu\n", *IN_param);
        test_state = Uart1Response2Received;
    }
}

void linux_PI_response_3
      (const asn1SccMyInteger *IN_param)
{
    if(test_state == Uart3Test1Sent) {
        test_param = *IN_param;
        printf("Got response from UART3: %lu\n", *IN_param);
        test_state = Uart3Response1Received;
    }
    else if(test_state == Uart3Test2Sent) {
        test_param = *IN_param;
        printf("Got response from UART3: %lu\n", *IN_param);
        test_state = Uart3Response2Received;
    }
}

void linux_PI_trigger( void )
{
    switch(test_state)
    {
        case Initial:
            linux_RI_test_3(&test_param);
            test_state = Uart3Test1Sent;
            break;
        case Uart3Test1Sent:
            break;
        case Uart3Response1Received:
            linux_RI_test_3(&test_param);
            test_state = Uart3Test2Sent;
            break;
        case Uart3Test2Sent:
            break;
        case Uart3Response2Received:
            linux_RI_test_1(&test_param);
            test_state = Uart1Test1Sent;
            break;
        case Uart1Test1Sent:
            break;
        case Uart1Response1Received:
            linux_RI_test_1(&test_param);
            test_state = Uart1Test2Sent;
            break;
        case Uart1Test2Sent:
            break;
        case Uart1Response2Received:
            break;
    }
}
