/* Body file for function samv71
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "samrh71.h"
//#include <stdio.h>

void samrh71_startup(void)
{
}

void samrh71_PI_test_1
      (const asn1SccMyInteger *IN_param)

{
    asn1SccMyInteger param = (*IN_param) + 1;
    samrh71_RI_response_1(&param);
}

void samrh71_PI_test_3
      (const asn1SccMyInteger *IN_param)
{
    asn1SccMyInteger param = (*IN_param) + 1;
    samrh71_RI_response_3(&param);
}
