/* Body file for function pinger
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "pinger.h"
#include <rtems.h>
//#include <stdio.h>

#define DATA_SIZE 8192U

volatile bool test_result = true;
volatile bool packet_ok = false;
volatile uint32_t counter = 0;

asn1SccMySeq spw_data;

void pinger_startup(void)
{
  spw_data.id = 42;
  spw_data.destination_id = 45;
  for(uint32_t i = 0; i < DATA_SIZE; i++){
    spw_data.data.arr[i] = 0xDE;
  }
}

void pinger_PI_trigger(void)
{
  rtems_task_wake_after(50);
  pinger_RI_ping(&spw_data);
}

void pinger_PI_pong(const asn1SccMySeq *IN_PI_1)
{
  packet_ok = true;

  if(IN_PI_1->id != 47 || IN_PI_1->destination_id != 50){
    packet_ok = false;
  }

  for(uint32_t i = 0; i < DATA_SIZE; i++){
    if(IN_PI_1->data.arr[i] != 0x13){
      packet_ok = false;
    }
  }

  if(!packet_ok){
    test_result = false;
  }

  counter++;

  if(counter >= 5){
    asm volatile("nop");
  }
}
